# Generated by Django 2.0.13 on 2019-10-26 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 8, 44, 563193, tzinfo=utc))),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
